# Generated by Django 4.2.11 on 2024-11-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managebanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeonseoption',
            name='dcls_month',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='CreditLoanOption',
            fields=[
                ('option_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dcls_month', models.CharField(max_length=6, null=True)),
                ('crdt_prdt_type', models.CharField(max_length=1, null=True)),
                ('crdt_lend_rate_type', models.CharField(max_length=1, null=True)),
                ('crdt_lend_rate_type_nm', models.CharField(max_length=255, null=True)),
                ('crdt_grad_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_4', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_5', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_6', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_10', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_11', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_12', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_13', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crdt_grad_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managebanks.financialproduct')),
            ],
        ),
    ]
