# Generated by Django 4.2.16 on 2024-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebanks', '0003_remove_financialproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcompany',
            name='homepage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
