# Generated by Django 4.2.16 on 2024-11-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebanks', '0004_financialcompany_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialcompany',
            name='homepage',
        ),
    ]
