# Generated by Django 4.2.16 on 2024-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebanks', '0005_remove_financialcompany_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcompany',
            name='homp_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
