# Generated by Django 4.2.16 on 2024-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_grade',
        ),
    ]
